steps:
  # Pre-existing step in the pipeline (example)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'echo "Starting build process..."']

  # New ubuntu step you want to add
  - name: 'ubuntu'
    args: ['echo', 'Hello, world!']

options:
  logging: CLOUD_LOGGING_ONLY  # You can add or modify this depending on your logging preference