steps:
  # Pre-existing step in the pipeline (example)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'echo "Starting build process..."']

  # New ubuntu step to echo "Hello, world!"
  - name: 'ubuntu'
    args: ['echo', 'Hello, world!']

# Set options including the machine type
options:
  machineType: 'E2_HIGHCPU_16'  # Select machine type with 16 GB memory
  logging: CLOUD_LOGGING_ONLY   # Optional - Set logging preference (can customize based on your needs)